data_homepage:
    path:     /hello/{name}
    defaults: { _controller: DataBundle:Default:index }

data_create_product:
    path:     /product/create
    defaults: { _controller: DataBundle:Default:create }

data_show_product:
    path:     /product/show/{id}
    defaults: { _controller: DataBundle:Default:show }

data_update_product:
    path:     /product/update/{id}
    defaults: { _controller: DataBundle:Default:update }

data_delete_product:
    path:     /product/delete/{id}
    defaults: { _controller: DataBundle:Default:delete }

data_show_product_by_category:
    path:     /product/show-by-category/{id}
    defaults: { _controller: DataBundle:Default:showProducts }